# FRONTEND BUILT ONLY ON AMD64

# DIST-STEP1: BUILD THE BACKEND
FROM golang:1.20-buster AS builder_backend
WORKDIR /home/
COPY ./build/filestash_w_frontend ./
RUN apt-get update > /dev/null && \
    apt-get install -y libvips-dev curl make > /dev/null 2>&1 && \
    make build_init && \
    make build_backend && \
    mkdir -p ./dist/data/state/config/ && \
    cp config/config.json ./dist/data/state/config/config.json
